name: Forza Rewards

on:
  schedule:
    - cron: '0 0 * * 0'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 2.7
      uses: actions/setup-python@v1
      with:
        python-version: 2.7
    - name: Claim Reward
      run: |
        python rewards.py "${{ secrets.COOKIE_FORZA }}" > output.txt
        cat output.txt
    - name: Set up Python 3.6
      uses: actions/setup-python@v1
      with:
        python-version: 3.6
    - name: Post to Discord
      run: |
        pip3 install requests
        python3 discord.py '${{ secrets.DISCORD_WEBHOOK }}'
